bash_dep=$(\pwd)/bash_dep

source $bash_dep/ps1.sh

export MSDOS="enable"

source $bash_dep/msdos.sh

alias epindows=$bash_dep/epindows.sh #TODO

\echo -e 'Microsoft(R) Windows DOS\n(C)Copyright Microsoft Corp 1990-2001.'
