set encoding=utf-8 fileencodings=
syntax on

set number
set cc=80

autocmd Filetype make setlocal noexpandtab

set list listchars=tab:»·,trail:·

set ts=4 sw=4

start
set mouse=a

colorscheme wildcharm

nnoremap <C-x> :wq<CR>
nnoremap <C-s> :w<CR>
nnoremap <C-q> :q!<CR>
nnoremap <C-f> :ClangFormat<CR>
nnoremap <C-y> :redo<CR>
nnoremap <C-z> :u<CR>
nnoremap <C-t> :sus<CR>

inoremap <C-x> <Esc>:wq<CR>
inoremap <C-s> <Esc>:w<CR>i
inoremap <C-q> <Esc>:q!<CR>
inoremap <C-f> <Esc>:ClangFormat<CR>i
inoremap <C-z> <Esc>:u<CR>i
inoremap <C-y> <Esc>:redo<CR>i
inoremap <C-t> <Esc>:sus<CR>

vnoremap <C-c> "+y
vnoremap <C-v> "+p
vnoremap <C-x> "+d
vnoremap <BS> d
inoremap <C-v> <Esc>v"+p<Esc>i
nnoremap <C-v> v"+p<Esc>
