;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/jaagr/polybar
;
;   The README contains alot of information
;
;==========================================================

[colors]
white = #FFFFFF

light_blue = #478EEF
blue = #245DDC
dark_blue = #1645AE

active_blue=#56a3ff
inactive_blue=#1951ba

green = #1B901B
dark_green = #0A4B26

[bar/windows]
width = 100%
height = 32
bottom = true

gradient = true
background-0 = ${colors.light_blue}
background-1 = ${colors.blue}
background-2 = ${colors.dark_blue}

foreground=${colors.white}

border-top-size = 2
border-top-color = ${colors.light_blue}

modules-left = start xworkspaces
modules-right = date

[module/start]
type = custom/text
label = "Start"
label-background = ${colors.green}
label-padding = 4

;TODO
click-left = exec rofi -show drun

[module/xworkspaces]
type = internal/xworkspaces
format = <label-state>
format-padding = 1

label-active = %name%
label-active-background = ${colors.active_blue}
label-active-padding = 1
label-active-margin = 1px

label-occupied = %name%
label-occupied-background = ${colors.inactive_blue}
label-occupied-padding = 1
label-occupied-margin = 1px

label-urgent = %name%
label-urgent-background = #FF0000
label-urgent-padding = 1
label-urgent-margin = 1px

label-empty = %name%
label-empty-foreground = #00FF00
label-empty-padding = 1
label-empty-margin = 1px

[module/date]
type = internal/date
interval = 5

date =

time = %I:%M %p
time-alt = %I:%M %p

format-background = ${colors.active_blue}
format-padding = 2

label = %date% %time%
